# Generated by Django 4.0.2 on 2022-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full attribute name')),
                ('value', models.CharField(max_length=255, verbose_name='value of attribute')),
                ('slug', models.CharField(max_length=255, verbose_name='slug for attribute:<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
            },
        ),
    ]
