# Generated by Django 4.0.2 on 2022-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full category name')),
                ('slug', models.CharField(max_length=255, verbose_name='slug for product')),
            ],
            options={
                'verbose_name': 'product category name',
                'verbose_name_plural': 'product category names',
            },
        ),
    ]
