# Generated by Django 4.0.2 on 2022-02-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categoryattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='full product name')),
                ('release_date', models.DateField(verbose_name='product release date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='product price')),
                ('summary', models.TextField(verbose_name='summary of the product')),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='product discount')),
                ('amount', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='product rate')),
                ('slug', models.CharField(max_length=255, verbose_name='slug for product')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
                ('manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufacturer')),
            ],
        ),
    ]
