# Generated by Django 4.0.2 on 2022-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'prodcuts'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='full product name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for attribute:<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for manufacturer:<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for product'),
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attribute',
        ),
        migrations.AlterModelTable(
            name='categoryattribute',
            table='catgory_attribute',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_catogory',
        ),
    ]
