# Generated by Django 4.0.2 on 2022-02-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_remove_product_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
                'db_table': 'product_attribute',
            },
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for attribute'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for manufacturer'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug for category'),
        ),
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
