# Generated by Django 4.0.2 on 2022-02-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productattribute_alter_attribute_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'product attribute', 'verbose_name_plural': 'product attributes'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(default=None, max_length=255, verbose_name='atribute value'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productattribute',
            table='product_attribute',
        ),
    ]
