# Generated by Django 4.0.2 on 2022-02-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
    ]
