# Generated by Django 4.0.2 on 2022-02-20 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, verbose_name='product discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='product rate'),
        ),
    ]
