# Generated by Django 4.0.2 on 2022-02-21 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_discount_alter_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(null=True, verbose_name='product release date'),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
