# Generated by Django 4.0.2 on 2022-02-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_amount_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='product_id',
            new_name='product',
        ),
    ]
