# Generated by Django 3.2 on 2022-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='user login')),
                ('password', models.CharField(max_length=255, verbose_name='user password')),
                ('username', models.CharField(max_length=255, verbose_name='user name')),
            ],
        ),
    ]
